version: "3"

services:  
  webserver:
    image: minervaprime/demo-webserver:v1
    ports:
      - "81:80"
    deploy:
      replicas: 2
      restart_policy:
        condition: none
      update_config:
        parallelism: 1
        failure_action: rollback

  nodeapp:
    image: minervaprime/demo-app:v1
    deploy:
      replicas: 2
      restart_policy:
        condition: none
      update_config:
        parallelism: 1
        failure_action: rollback
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3