version: "3"

services:  
  webserver:
    image: minervaprime/demo-webserver:v1
    ports:
      - "80:80"
    deploy:
      replicas: 2
      restart_policy:
        condition: none
      update_config:
        parallelism: 1
        failure_action: rollback
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/"]
      interval: 30s
      timeout: 5s
      retries: 3

  nodeapp:
    image: minervaprime/demo-app:v2
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    deploy:
      replicas: 2
      restart_policy:
        condition: none
      update_config:
        parallelism: 1
        failure_action: rollback
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3

  redis:
    image: redis:4-alpine
    deploy:
      replicas: 2
      restart_policy:
        condition: any
    volumes:
      - redisdatavol:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  redisdatavol: